# https://www.home-assistant.io/integrations/default_config/
# default_config:

# https://www.home-assistant.io/integrations/homeassistant/
homeassistant:
  debug: true

# Manual list of components from default_config (minus media/stream)
config:

# https://www.home-assistant.io/integrations/logger/
logger:
  default: info
  logs:
    custom_components.rixens: debug
